@extends('layouts.blog')

@section('content')
<div class="mx-auto max-w-7xl overflow-x-hidden px-4 md:px-12">
    <section class="border-b border-[#c5c5d7]/30 py-12 md:py-20">
        <div class="flex flex-col justify-between gap-8 md:flex-row md:items-end md:gap-10">
            <div class="max-w-2xl">
                <p class="mb-4 text-[10px] font-semibold uppercase tracking-widest text-[#1a35ca]">{{ __('blog.home_eyebrow') }}</p>
                <h1 class="font-display text-4xl font-bold leading-tight tracking-tight md:text-5xl">{{ __('blog.hero_title') }}</h1>
                <p class="mt-5 max-w-xl text-lg leading-8 text-[#444655] dark:text-[#c5c5d7]">{{ __('blog.hero_description') }}</p>
            </div>
            <div class="flex w-full max-w-sm gap-5 rounded-xl border border-[#c5c5d7]/30 bg-white p-5 shadow-sm dark:bg-[#171d34] md:w-auto">
                <div><p class="text-[10px] uppercase tracking-widest text-[#757686]">{{ __('blog.published_notes') }}</p><p class="mt-2 font-display text-2xl font-bold">{{ $publishedCount }} <span class="font-body text-xs font-normal text-[#1a35ca]">{{ __('blog.entries') }}</span></p></div>
                <div class="w-px bg-[#c5c5d7]/40"></div>
                <div><p class="text-[10px] uppercase tracking-widest text-[#757686]">{{ __('blog.categories') }}</p><p class="mt-2 font-display text-2xl font-bold">{{ $categoryCount }} <span class="font-body text-xs font-semibold text-emerald-500">{{ __('blog.active') }}</span></p></div>
            </div>
        </div>
        <div class="mt-8 flex flex-wrap gap-2"><a href="{{ route('articles.index') }}" class="rounded-full bg-[#1a35ca] px-4 py-2 text-xs font-semibold text-white">{{ __('blog.all_entries') }}</a>@foreach($categories as $category)<a href="{{ route('categories.show', $category) }}" class="rounded-full bg-[#eaedff] px-4 py-2 text-xs font-medium text-[#444655] hover:bg-[#dae2fd] dark:bg-[#202947] dark:text-[#c5c5d7]">{{ $category->name }} <span class="ml-1 text-[#757686]">{{ $category->articles_count }}</span></a>@endforeach</div>
    </section>

    @if($featured)
        <section class="py-8"><div class="overflow-hidden rounded-xl border border-[#c5c5d7]/30 bg-white shadow-sm dark:bg-[#171d34]"><div class="grid md:grid-cols-2"><div class="flex min-w-0 flex-col justify-between p-6 md:p-8"><div><div class="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-wider text-[#1a35ca]"><span class="rounded bg-[#dfe0ff] px-2 py-1">{{ $featured->category?->name ?? 'Research' }}</span><span class="text-[#757686]">· {{ $featured->published_at->format('d M Y') }}</span></div><h2 class="mt-5 font-display text-3xl font-semibold leading-tight md:text-4xl">{{ $featured->title }}</h2><p class="mt-5 leading-7 text-[#444655] dark:text-[#c5c5d7]">{{ $featured->excerpt }}</p></div><a href="{{ route('articles.show', $featured) }}" class="mt-8 inline-flex items-center gap-2 text-sm font-semibold text-[#1a35ca]">{{ __('blog.read_monograph') }} <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" class="size-4" aria-hidden="true"><path d="M5 19 19 5M9 5h10v10"/></svg></a></div>@if($featured->cover_image)<img src="{{ asset('storage/'.$featured->cover_image) }}" alt="{{ $featured->cover_image_alt ?: 'Cover for '.$featured->title }}" class="h-56 w-full object-cover md:h-full">@else<div class="grid min-h-56 place-items-center bg-[#eef0ff] text-[#1a35ca]"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" class="size-12" aria-hidden="true"><path d="M7 3h7l3 3v15H7z"/><path d="M14 3v4h4M10 12h4M10 16h4"/></svg></div>@endif</div></div></section>
    @endif

    <section class="grid min-w-0 gap-8 pb-16 lg:grid-cols-3"><div class="min-w-0 lg:col-span-2"><div class="mb-5 flex min-w-0 items-center justify-between gap-3"><h2 class="flex min-w-0 items-center gap-2 font-display text-xl font-semibold"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" class="size-5 shrink-0 text-[#1a35ca]" aria-hidden="true"><path d="M7 3h7l3 3v15H7z"/><path d="M10 12h4M10 16h4"/></svg><span>{{ __('blog.latest_research') }}</span></h2><span class="hidden shrink-0 font-mono text-[10px] uppercase tracking-widest text-[#757686] sm:block">{{ __('blog.chronological_feed') }}</span></div><div class="space-y-4">@forelse($articles->skip(1) as $article)<a href="{{ route('articles.show', $article) }}" class="group block max-w-full overflow-hidden rounded-xl border border-[#c5c5d7]/30 bg-white transition-colors hover:border-[#3b52e2] dark:bg-[#171d34]"><div class="flex min-w-0"><div class="flex min-w-0 flex-1 flex-col p-5"><div class="flex flex-wrap items-center gap-2 text-[10px] font-semibold uppercase tracking-wider text-[#1a35ca]"><span class="rounded bg-[#dfe0ff] px-2 py-1">{{ $article->category?->name ?? 'Note' }}</span><span class="text-[#757686]">· {{ $article->published_at->format('d M Y') }}</span></div><h3 class="mt-3 break-words font-display text-xl font-semibold group-hover:text-[#1a35ca]">{{ $article->title }}</h3><p class="mt-2 line-clamp-2 break-words text-sm leading-6 text-[#444655] dark:text-[#c5c5d7]">{{ $article->excerpt }}</p><div class="mt-auto flex items-center justify-end pt-5 text-xs"><span class="inline-flex shrink-0 items-center gap-1 text-[#1a35ca]">{{ __('blog.read') }} <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" class="size-4" aria-hidden="true"><path d="M5 19 19 5M9 5h10v10"/></svg></span></div></div>@if($article->cover_image)<img src="{{ asset('storage/'.$article->cover_image) }}" alt="{{ $article->cover_image_alt ?: 'Cover for '.$article->title }}" class="hidden w-44 shrink-0 object-cover transition-transform duration-300 group-hover:scale-[1.03] sm:block md:w-52">@endif</div></a>@empty<div class="rounded-xl border border-dashed border-[#c5c5d7] p-10 text-center text-sm text-[#757686]">{{ __('blog.no_articles') }}</div>@endforelse</div></div>
        <aside class="space-y-5"><div class="rounded-xl border border-[#c5c5d7]/30 bg-white p-5 dark:bg-[#171d34]"><div class="flex items-center justify-between"><h2 class="flex items-center gap-2 font-display font-semibold"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" class="size-5 text-[#1a35ca]" aria-hidden="true"><path d="M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h6v6h-6z"/></svg>{{ __('blog.journal_topics') }}</h2><span class="rounded-full bg-emerald-50 px-2 py-1 text-[10px] text-emerald-600">{{ $categoryCount }} {{ __('blog.active') }}</span></div><div class="mt-4 space-y-2">@foreach($categories as $category)<a href="{{ route('categories.show', $category) }}" class="flex items-center justify-between rounded-lg bg-[#f2f3ff] px-3 py-2.5 text-sm transition hover:bg-[#eaedff] dark:bg-[#202947]"><span class="font-medium">{{ $category->name }}</span><span class="font-mono text-xs text-[#1a35ca]">{{ $category->articles_count }}</span></a>@endforeach</div></div><div class="rounded-xl border border-[#c5c5d7]/30 bg-[#f2f3ff] p-5 dark:bg-[#202947]"><h2 class="flex items-center gap-2 font-display font-semibold"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" class="size-5 text-[#1a35ca]" aria-hidden="true"><path d="m20 13-7 7-9-9V4h7z"/><circle cx="8.5" cy="8.5" r="1"/></svg>{{ __('blog.active_tags') }}</h2><div class="mt-4 flex flex-wrap gap-2">@foreach($popularTags as $tag)<a href="{{ route('tags.show', $tag) }}" class="rounded-full bg-white px-3 py-1.5 text-xs font-medium text-[#444655] shadow-sm transition hover:text-[#1a35ca] dark:bg-[#171d34] dark:text-[#c5c5d7]">#{{ $tag->name }} <span class="text-[#757686]">{{ $tag->articles_count }}</span></a>@endforeach</div></div><div class="rounded-xl border border-[#c5c5d7]/30 bg-white p-5 dark:bg-[#171d34]"><h2 class="flex items-center gap-2 font-display font-semibold"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" class="size-5 text-[#1a35ca]" aria-hidden="true"><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2Z"/></svg>{{ __('blog.reading_queue') }}</h2><ol class="mt-4 space-y-3 text-xs text-[#444655] dark:text-[#c5c5d7]"><li><span class="mr-2 text-[#1a35ca]">01</span>{{ __('blog.queue_one') }}</li><li><span class="mr-2 text-[#1a35ca]">02</span>{{ __('blog.queue_two') }}</li><li><span class="mr-2 text-[#1a35ca]">03</span>{{ __('blog.queue_three') }}</li></ol></div></aside></section>
</div>
@endsection
